name: Build, Pack & Publish

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
                             
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Install .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Download libraries
      run: ./download_package.sh

    - name: Build
      run: dotnet build src/DtronixPdf -c Release
      
    - name: Pack
      run: dotnet pack src/DtronixPdf -c Release -o ./artifacts
      
    - name: Unit tests
      run: dotnet test src/DtronixPdf.Tests -c Release
      
    - name: Export artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts/*.nupkg
        
    - name: Get tag name
      if: startsWith(github.ref, 'refs/tags/')
      uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: "DtronixPdf ${{ steps.tagName.outputs.tag }} Released"
        files: artifacts/*.nupkg
      
    - name: Push Nuget packages
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.ORG_NUGET_AUTH_TOKEN }} --skip-duplicate